spring :
  application :
    name : eureka-discovery-server

server :
  port : 9083

eureka :
  client :
      register-with-eureka : false
      fetch-registry : false
  instance :
      hostname : localhost
      non-secure-port : 9083
  