spring.application.name=actuator-service


management.endpoints.access.default=UNRESTRICTED
management.endpoint.health.show-details=ALWAYS
management.security.enabled=false

management.endpoints.web.exposure.include=*