spring.application.name=oauth-service



#Github login 

spring.security.oauth2.client.registration.github.client-id=Ov23liWeHOX0vR0WKiib
spring.security.oauth2.client.registration.github.client-secret=5aae025968e58f01022a0637811b4e159fe1583b


# Google Login 

spring.security.oauth2.client.registration.google.client-id=Ov23liWeHOX0vR0WKiib
spring.security.oauth2.client.registration.google.client-secret=Ov23liWeHOX0vR0WKiib


logging.level.org.springframework.security=TRACE